PARAMETERS PCODIGOS
CODIMPR = 0
PCODIGOS=UPPER(PCODIGOS)
DO WHILE !EMPTY(PCODIGOS)
	DO CASE
	CASE LEFT(PCODIGOS,1)='E'	&& ELITE
		CODIMPR = CODIMPR + 1
	CASE LEFT(PCODIGOS,1)='P'	&& PROPORCIONAL
		CODIMPR = CODIMPR + 2
	CASE LEFT(PCODIGOS,1)='C'	&& CONDENSADO
		CODIMPR = CODIMPR + 4
	CASE LEFT(PCODIGOS,1)='N'	&& NEGRITA
		CODIMPR = CODIMPR + 8
	CASE LEFT(PCODIGOS,1)='D'	&& DOBLE GOLPE
		CODIMPR = CODIMPR + 16
	CASE LEFT(PCODIGOS,1)='G'	&& GRANDE
		CODIMPR = CODIMPR + 32
	CASE LEFT(PCODIGOS,1)='I'	&& ITALICA
		CODIMPR = CODIMPR + 64
	CASE LEFT(PCODIGOS,1)='S'	&& SUBRAYADO
		CODIMPR = CODIMPR + 128
	ENDCASE
	PCODIGOS = IIF(LEN(PCODIGOS)=1,'',SUBSTR(PCODIGOS,2))
ENDDO
RETURN CHR(27)+'!'+CHR(CODIMPR)

