SET EXCLUSIVE ON
*SET PATH TO DATOS\;SISTEMA\
SET DELETED ON 
*OPEN DATABASE AMMBA.DBC
USE bonos
PACK
reindex
SET ORDER TO BONOS   && CUPON*100+ORDEN
*MESSAGEBOX('BORRANDO DUBLICADOS')
MESSAGE('BORRANDO DUPLICADOS')
bb=0
GO TOP 
DO WHILE !EOF()
	IF bb=cupon*100+orden
		DELETE
	ENDIF
	bb=cupon*100+orden
	SKIP
ENDDO
PACK
REINDEX 
CLOSE ALL
